### ISSUE TITLE
Use standard NDEBUG instead of custom DEBUG

### ISSUE THREAD

**Issue by aartaka** [khushal-banks/log_bank#1]
Hi!

Seen your project on r/C_programming and decided to check it out. While I haven't yet used it, I've got a look at the code and found that you're using `DEBUG` macro to control whether `TRACE` does anything.

There's a standard solution for that: `NDEBUG`. You can see how it's working [on this `assert` reference page](https://en.cppreference.com/w/c/error/assert). But the gist of it is:
- If `NDEBUG` is present, expand the macro to `((void*)0)` (or an equivalent). No-op, effectively.
- If NDEBUG is not present, then we're in debug mode, so expand to the normal debugging code.

Am I missing something? Why not try `NDEBUG`?

**Comment by khushal-banks** [comment]
Hello @aartaka, Thank you so much for your feedback.

There is no specific reason to use DEBUG instead of NDEBUG.
Basically, using NDEBUG requires it to be defined for release mode.

Some configuration parameters from [Makefile](https://github.com/khushal-banks/log_bank/blob/main/log_bank/Makefile) of this project.
```
# debug
DEFS_DEBUG              = -DDEBUG
DEFS_DEBUG              += -DLOG_LEVEL=1 -DLOG_FILE_DIR=\"logs/\"
CFLAGS_DEBUG         := -ggdb -g3 -Og
CFLAGS_DEBUG        += $(DEFS_DEBUG)

# release
DEFS_RELEASE          := -DNDEBUG
DEFS_RELEASE          += -DLOG_LEVEL=3 -DLOG_FILE_DIR=\"logs/\"
CFLAGS_RELEASE      := -O3
CFLAGS_RELEASE	    += $(DEFS_RELEASE)
```

So, NDEBUG is supported.

> You are not missing anything. I will add your suggested modification in the next commit. :)
> I will close this issue based on inactivity after next commit.
> Thank you once again.

**Comment by aartaka** [comment]
Oh, I see. Missed the Makefile. 

Even though I still am uneasy about the use of `DEBUG` where a mere `NDEBUG` (or its absence) would work, I'll close the issue.
