### ISSUE TITLE
[Feature request] Logging to a well-defined queue 

### ISSUE THREAD

**Issue by jgabaut** [khushal-banks/log_bank#2]
Hi, I was one of the stargazers for your previous implementation and I remember participating in some issues, like suggesting the color support (whose code looks quite different here!) :smile:

This implementation seems really clean and I very much like it.

I'd love to use this with a project (over my own log library), but one feature I'd like (which I don't have in my own, and I don't think I can attain here with the currently exposed features, but correct me if I'm wrong) is being able to send the log messages into a queue, from which I would be able to pop them one at a time from somewhere else.

The key would be the queue implementation, which would need to be robust. I don't know if the current API can be wrapped into something that's working. The access semantics would need the queue to be expandable (so that it can grow when it's full and not being drained in time), and the pop operation to remove the oldest entry and use it in a consumer.

I'm guessing a free list for available slots could be used, but then I imagine there would be a need for compacting the queue, and with the "stop-the-world" is not the best idea I guess... You catch my drift.

I would like to participate, still considering the limits of my competence, since if we want to do this properly there may be a need to some proper OS interop, which you've done really cleanly around the lib.

Are you interested in the idea?

**Comment by khushal-banks** [comment]
Hello @jgabaut, So good to see you. 
This implementation includes all necessary changes we discussed last time.
- Color Support
- Doxygen Comments
- [Example](https://github.com/khushal-banks/log_bank/blob/main/examples/c/src/example.c)
- [Makefile](https://github.com/khushal-banks/log_bank/blob/main/log_bank/Makefile)
- I also added some compile time flags to easily use this as a static library (.a file) without the need to modify source code for project specific changes.

These changes exist because of your suggestions. I am looking forward to hear more from you. :)
I renamed the library because log-libc gave me some kind of standard library vibes.

**Comment by jgabaut** [comment]
I noted all the changes and I am really stoked.

I very much like the example, it drew me closer to the idea of using this. Also the valuable Makefile and the static option are keys to easy usage, thanks for your work!

Let me know if you need any help or contribution about the feature request.

**Comment by khushal-banks** [comment]
I will need to think more about queue based implementation.
Current implementation doesn't include it.

Can you explain why would we need a queue for logging? I am struggling to reason the need of one.

**Comment by jgabaut** [comment]
I'm thinking of using the same log library both for "debugging" logs (think, to a file, which this library does plenty of I think) and "user-facing" logs. This second kind of logs would maybe be drained at a "steady" pace by a consumer displaying them into a window, or something like that.

It may be that my reasoning is flawed and my idea isn't the solution to the problem. My issue -the need for the queue, if there is one- is that log messages can be "produced" asyncronously from the "pop/display" rate of them, and I would like my log library to embed the memory support. I don't know if:

- A ring buffer is suitable for this ?
- Does this usage idea justify a queue, would it meet the needs?
- Is this too complex of a support to ask from the log library? Storing to a file is surely and by large the main usage, is having a in-memory log a bad idea?

**Comment by khushal-banks** [comment]
What i understood from your requirement is that we need:
- int log_write_queue(const char* fmt, ...); to append to a queue
- int log_read_queue(char* message, sizeof size, int level); to read from queue
- and a dynamic queue with some size limitations.
- and either updating or ignoring new append to queues when it is full.

I will answer your recent questions based on my understanding.
- A ring buffer is suitable for this ? I don't think buffer implementation would have any effect but i am not certain.
- Does this usage idea justify a queue, would it meet the needs? Yes it can do it but not properly because both logging requests and queue read can be of different speed and thus, may make this library memory resource heavy.
- Is this too complex of a support to ask from the log library? No we can do it alternatively.

**Comment by khushal-banks** [comment]
I think there is no difference between log messages and user facing logs .. right?
Only difference is that they are used differently.

This can be done in many alternate ways:
1. We can read from the files directly and display to user at the speed we want.
2. We can use this library to log on UART stream which will display it to user on UART
3. We can use this library to log on UART stream and then, we can read from a different application through UART. This way we can control every related parameters and even the graphical user interface.

I would like to hear your thoughts on above discussed alternate ways.

**Comment by jgabaut** [comment]
The interface you described seems close to the ideal one.

The key points that spring to mind are:
- Could we include a mechanism that, in a pinch, can be used to turn all calls to our main log function, be indistinguishable from the already-existing main log function (what I mean is, some kind of control over the behaviour of your `log_write_queue()` func).
  - Since `log_write_queue()` would be a different call than the main log function (the one used for file-logging), some way of expressing the need of "keeping them tight" should be included.
- A ring buffer would start overwriting its contents when it's full. If the queue implements this behaviour (allows oldest message's space to be overwritten when out of memory), I'd say it's close to ring buffer memory semantics. The alternative don't look good, since erroring and not saving the message when full would mean the same number of messages (but instead, the newly-sent ones) are lost. The growable (and thus, potentially heavy memory consumption) aspect is the spicy one.


I want to look more into UART streams since I don't know them, will report it in short time. If you have some links to suggest me, I'd happily take a couple.

**Comment by jgabaut** [comment]
> 
>     * int log_read_queue(char* message, sizeof size, int level); to read from queue
> 

I'm guessing one would need to pass level and size to any queue read. Maybe a structure could embed all three and we could wrap this call with convenience functions to fill or allocate the boxed thingy.

**Comment by jgabaut** [comment]
> What is the difference between normal log messages written to files and user facing logs? Are user facing logs also debugging logs related to what is happening in the source code?
> 
> What are your thoughts on ["alternate ways" mentioned here?](https://github.com/khushal-banks/log_bank/issues/2#issuecomment-2020596832)

User-facing logs are the log calls that instead of going to the file, are meant to be readily available for the context to be used by the consumer (ideally without the file semantics, using memory semantics instead -in any structured way, maybe files are good actually-) that may use the "read" message for any usage (I'd like to print them to the screen, in a scrolling terminal).

I'm questioning my question, since I don't really know if this makes any sense.

About the mentioned alternatives, I don't know about UART streams and haven't been lucky finding good documentation. Will need more time to look into that. Can you help me with some pointers in the right direction?

**Comment by khushal-banks** [comment]
> * -The idea of reading from the generated file is doable, and if you think that would be easier/more appropriate in any way, I'm all for it if it can get my idea going. I would then just need to be able to differentiate the target of user-code log calls (to tell apart which ones are for the window/consumer).

Can we create a project named log_manage? which will handle the GUI part. This way we can support other libraries (used for logging) in that project. GUI project will take care of how to show logged information, search logs based on date and time stamp and live streaming feature directly from file. How does that sound ?

**Comment by khushal-banks** [comment]
> I'd like to print them to the screen, in a scrolling terminal

Yes we will name it live streaming

**Comment by khushal-banks** [comment]
> About the mentioned alternatives, I don't know about UART streams and haven't been lucky finding good documentation. Will need more time to look into that. Can you help me with some pointers in the right direction?

I will create a doc for this. This library supports UART based logging (not used right now). In that document i will write everything about how to use this library to stream logs to pseudo or physical uart interfaces

**Comment by khushal-banks** [comment]
> User-facing logs are the log calls that instead of going to the file, are meant to be readily available for the context to be used by the consumer

Understood. I believe UART is meant for this purpose only. Or we can read from file as well. I will explore more on this and hopefully start working on this [in log_manage project as discussed here](https://github.com/khushal-banks/log_bank/issues/2#issuecomment-2020691620).

**Comment by khushal-banks** [comment]
> but I'd encourage keeping it minimal. The users of this library would ideally still approach it with the same needs

Understood. Let's sleep on it. I will write to you once i have something useful to share.
Queue based implementation doesn't feel right at the moment. I will keep in mind that we need something minimal.

Thank you for sharing your thoughts on this feature.

**Comment by jgabaut** [comment]
If you would pardon both my self-quoting and the personal link, I'd share an example of this:

> 
> Think of this: at a later time, we could also add the memory-hungry version avoiding files 
>

I have this messy library I used to convert some small png's to in-memory sprites [shameless](https://github.com/jgabaut/sprites4curses). In early versions (and I haven't yet updated mentions of this in the README.......) the only supported "input" for the consumer functions was file-reading. But then I added loading from a file to avoid reading the same file multiple times to loop. Then I avoided the file read entirely by compiling the previous-file-based representation to wasteful C structures that can be built into the user-code program at build time.

**Comment by khushal-banks** [comment]
> I will create a doc for this. This library supports UART based logging

Here is an [example for linux_uart](https://github.com/khushal-banks/log_bank/blob/main/examples/linux_uart/src/linux_uart.c) and doc [LINUX_UART.md](https://github.com/khushal-banks/log_bank/blob/main/docs/LINUX_UART.md)

Check if queue based implementation is still necessary for your use case.

**Comment by khushal-banks** [comment]
Do you need something like [this](https://docs.oracle.com/cd/E23521_01/doc.60/e26770/img/sbead_es_logs_display.png) ?
or maybe something like [this](https://mac-optimization.bestreviews.net/wp-content/uploads/sites/35/log-file-console-view.png) ?

**Comment by jgabaut** [comment]
I've looked at the resources here and it seems the example shows printing to a terminal device (proving that it can act like a file), but it doesn't seem to hold to my usage idea. Think of this:

```c
LOG_ITEM* pop_log(CTX* ctx, size_t size);
```

Any caller would be able to implement the use logic of `LOG_ITEM` by themselves.

The backing memory could be anything, even files, if the library would handle the required logic. The key being the `CTX` context, passed around and used to hold all references needed to keep up the facade for the interface client.

I'm now thinking that I could circument the queue complexity by actually using a ring buffer and just drawing its state. Oldest log would be deleted by ring semantics. Maybe this is more doable, but I still question if you see a general utility of if my usecase should be dealt with in a different project.

**Comment by khushal-banks** [comment]
See i believe it's not me who can decide how people would like to log their debug messages.
You clearly stated a different implementation. 
But, i believe this can also be done by defining all three of these functions as a wrapper around this library.
```
LOG_ITEM* pop_log(CTX* ctx, size_t size);
bool my_ncurses_draw_log(LOG_ITEM* msg, WINDOW* win, VEC2 coords);
bool my_raylib_draw_log(LOG_ITEM* msg, VEC2 bounds, VEC2 coords);
```

Does the function implementations you just shared exist in [sprites4curses](https://github.com/jgabaut/sprites4curses) ?
I am sorry but every time i see queue or ring buffer .. my mind translates it to memory which is synonym for expensive in my dictionary. I would love to do this for your project [sprites4curses](https://github.com/jgabaut/sprites4curses) if not already done. Maybe your project doesn't have access to files and you don't want file dependency. But trust me brother it would be best if logs are stored in files or transferred some where.

Based on my limited knowledge about the subject i can not support the idea of logging in stack or heap memory of the program (in queue or ring buffer). It would certainly lead to a bottleneck if you don't transfer it right away out of memory.

Do you agree with my idea of not using memory for logging?

**Comment by khushal-banks** [comment]
> One can always use this library independent of files. We can log information directly on stderr. without using any file.
> So, user will see the logged information on the terminal where he would execute the command to run his program.

Will this be sufficient for your project? It will neither use more memory and it will also not use any file.

**Comment by jgabaut** [comment]
I don't have an implementation of what I describe.

The core idea would be that if some way of retrieving all previous logs (from some resource store, wherever it may be), sequentially, was to be exposed; user code implementing any logic requiring access to previous logs would have an easier time.

I can totally understand if you don't agree this would be an useful feature to add.

About the memory requirements, storing into a file still needs memory... And that's okay. 

My request is mainly about being able to retrieve "unread" logs (such that for the pop operation to behave correctly from anywhere it is called on a specific log-list, it would need some context).

The backing memory could be shaped in nay way you may seem fit.

But the act of just printing into terminal has nothing to do with retrieving what what logged.

About wrapping existing functions to achieve this, I think it would be possible but I don't necessarily know the best way to do things cleanly so that user-code can have a great time. I think it would be possible and that's the reason for the feature request.

If I were to implement this in a non-very-generic way, I'd use a sized ring buffer (at most, x slots) and hook my log function to a (global???) ringbuf (or maybe, take a reference to one in the wrapping call) so that I can update the buffer.

About underlying operations:

- `pop()` would need to return the oldest unpopped value (not the newest one). I'm not sure this complies with ring buffer logic, I'm having trouble visualising if this would need constant compaction.
- `push()` would need to correctly add one item to the buffer.
  - Delete oldest when full

**Comment by khushal-banks** [comment]
> About the memory requirements, storing into a file still needs memory... And that's okay.

Files are stored on hard disk. So, it would not be expensive for the program. Memory used by program will be limited.

> The core idea would be that if some way of retrieving all previous logs (from some resource store, wherever it may be), sequentially, was to be exposed; user code implementing any logic requiring access to previous logs would have an easier time.

See this library is only meant to store logs. There is no retrieval happening yet.

By reading this long description i can fully understand what you don't want. 
**So yes this library as is will not be a able to fit your requirements.**

> Nothing wrong with offering those semantics from a storing memory which is, actually, a file (not on stack or heap, I mean. Think currently existing files. Maybe I'm circling back to your idea of log_manage with this). But how to design the library context interface??

Okay, good to see that we are finally on a common ground. log_manage will offer retrieval of logs. 

- **Let's discuss what you mean by library context interface?**
Do you mean CTX in the following function?
```
LOG_ITEM* pop_log(CTX* ctx, size_t size);
```

**Comment by khushal-banks** [comment]
If yes, then don't bother to think about it. It will be based on as you previously suggested.. memory. Ring buffer or queue what ever would seem fit.
Contained information would differ based on how we would like to display final output.

For example, if someone filtered unread messages from Jan-2024 to Mar-2024 every Saturday between 1:00 AM to 3:00 AM ..
You see context will depend on how would we filter the data.

If you are curious that why memory is suddenly not a problem for me.
Answer is, we will always show data say in a table.. table would have entries like 20. So, we will read many entries (not from files but from database like MySQL) and then we will show only 20.. when user clicks next next 20 entries when clicks back previous 20 entries.

Memory will not be an issue because log_manage would be a memory hungry program (not a library which needs to be light weight).

**Comment by khushal-banks** [comment]
Only question remains is that why you don't want to log information in files using log_bank.

So that your users can later use log_mange to retrieve information. :)

**Comment by jgabaut** [comment]
>     * **Let's discuss what you mean by library context interface?**
>       Do you mean CTX in the following function?

Yes, I was referring to that. As an example, this library has a context on what the "set level" is (to avoid logging calls below/above the target level). Any call to the library either provides the context explicitly as a parameter, or uses a globally-defined one. (I don't really know if this example is solid. My own log library does so by passing a "logger" struct to each call, and there's macro functions that pass a global default one, and I was thinking that the abstraction could still fit here).

I'm satisfied by your replies, and at this point I agree that such logic should not be placed together with the logger implementation; instead wrapping the logger with a custom function also updating the memory reference is to be preferred.

I was hoping to avoid this way since I don't really want to wrap all and every possible signature from the log library to be sure that my log calls actually update my -as an example- sized ring buffer. If not doing that, the user code would be confined to one (or a few) signatures from the log library... Sounds tedious. Problem is, I don't really know how to uncouple the responsibilities correctly on this one.

About the memory: imagine I need something like 6-7 message records max. I'd need to "read the latest unprinted one" (effectively, pop oldest, so that, if buffer was full prior to the pop, the was-second-oldest would not be delete by a new push -which would use the space freed by previoud pop correctly-).

It sounds messy but you can see what I would need this for by trying out the project using sprites4curses. That's where some of the logs are to be drawn... Don't want to put more links here, you can find it on my profile if you want to see.

> Only question remains is that why you don't want to log information in files using log_bank?
>
> So that your users can later use log_mange to retrieve information. :)

I don't have a problem with using file logging, in fact I have a -messy, not nearly as clean as this- function implementation at the moment. And it's not even my own log library, it's literally just a function I made... 

The main reason for this issue was just that I would like similar usage for my "display_notification()" function and my `log_tag()` functions. They would both take a message, but one would log to a file and one would store the message in a queue so that it can be rendered from a different point in the code, as soon as it's time. At the moment, my `display_notification()` is very bad and makes everything stop for a few millisecons after refreshing the render, in order to give time to each message to be visible. 

I'd instead like the logic to move into my frame-update loop, where I could check if a number of frames has passed since last `pop()`-and-`render()` and thus do it again. This would avoid the sleep (which is blocking my animations in other areas of the screen.).

Maybe I'm thinking of this all wrong.

As you can see, the problem is not really with `log_tag()` -which is bad and would likely also end up being replaced if I were to add a log library- but with this unrelated mumbo-jumbo. 

In any case, I think this issue got too long for its own good. I'd close it and suggest you open a new one, still about a new feature, which is more succint and to the point of what you think should/will be added. I'm sure you will come up with some ideas, and if not, I'm still happy we had time to talk about it! :smile:

**Comment by khushal-banks** [comment]
I am very sad to see this issue closed. To a degree i understand your requirement.

Here is my proposed solution.
1. Every logged message needs to go to a ring buffer .. queue size is fixed at compile time.
2. It should not be necessary to log information. One might like to use it as notification queue. So, this explains log_write_queue() function you mentioned.
3. How someone displays notification is entirely up to them, this explains log_pop() function you mentioned.

I checked out [animate.c](https://github.com/jgabaut/sprites4curses/blob/master/s4c-animate/animate.c) i see fprintf is used to log to a file. I believe you want to use LOG Macro provided by this library in place of fprintf.

This will give you nice looking string. But your requirement is these strings should go to a ring buffer.
You also mentioned this precisely in the title of this issue and explained it very well. I wished i had seen [animate.c](https://github.com/jgabaut/sprites4curses/blob/master/s4c-animate/animate.c) earlier.

I believe this is a nice enhancement to this library. It will extend the use case as well. 
Plus, this should be in the library someone who doesn't want to use a queue can simply set it's size to zero at compile time.

If you only want 2 APIs:
log_en_rbuffer() - this will write to buffer. when full it will replace existing entries. will keep going in circle.
log_de_rbuffer() - this will read and remove from rbuffer. it will always pop the oldest available entry.

Confirm details mentioned in this message is your requirement and Reopen this issue.

**Comment by jgabaut** [comment]
> If you only want 2 APIs: log_en_rbuffer() - this will write to buffer. when full it will replace existing entries. will keep going in circle. log_en_rbuffer will be used by this library only. User will write using LOG/TRACE macro.
> 
> log_de_rbuffer() - this will read and remove from rbuffer. it will always pop the oldest available entry.
> 
> Please, confirm details mentioned in this message is your requirement and Reopen this issue.

I think you understood the wanted feature, but not the reason for it. 

`animate.c` is not the target for this, I mentioned it since it was an example of adding differente memory semantics while keeping the premise of the interface. The log library may be used for `helapordo`, which is the client of `sprites4curses` used in the example.

Aside from this, I think all the other things you said are correct.

I'd still prefer if you opened a new issue, since it will have a more meaningful comment chain (and top post).

This can stay closed and mentioned there as a starting point, but I'm sure you could put a nice, short post to start the feature issue, if you want.

**Comment by khushal-banks** [comment]
I already started working on it. I am making as close integration with current library as possible.
You should should see it in a few days.

**Comment by khushal-banks** [comment]
Moved to Discussion #3
