### ISSUE TITLE
The static object for Debug build fails linking with example main

### ISSUE THREAD

**Issue by jgabaut** [khushal-banks/log_bank#28]
I tried using the static object `liblog_bank.a` with an example program.

Steps to reproduce:

- Clone `log_bank`
- Build `log_bank`. I just did:
  ```sh
    cd src && make
  ```
- Create `proj` directory
- Copy `build/Debug/liblog_bank.a` to `proj/lib/liblog_bank.a`
- Copy recursively `src/include` to `proj/include`
- `proj/src/main.c`:
  ```c
    #include "log_bank/log_bank.h"
    int main(void) {
      LOG(LOG_INFO, "Hello, World!\n");
      return 0;
    }
  ```
- Build command:
  ```sh
    gcc src/main.c -I ./include -L ./lib -l:liblog_bank.a -o hello_world
  ```
- Build fails at link stage. 
  - I checked the argument to `-l` and tried different strings before settling on full naming (`-l:liblog_bank.a`).
- Error:
  ```console
    logbank_test/src/main.c:5:(.text.startup+0x22): undefined reference to `log_get_level'
    /usr/bin/ld: logbank_test/src/main.c:5:(.text.startup+0x7c): undefined reference to `log_stamp_collector'
    /usr/bin/ld: logbank_test/src/main.c:5:(.text.startup+0x81): undefined reference to `log_get_factorylevel'
    /usr/bin/ld: logbank_test/src/main.c:5:(.text.startup+0xb5): undefined reference to `log_this'
    /usr/bin/ld: logbank_test/src/main.c:5:(.text.startup+0xee): undefined reference to `log_this'
  ```

I don't know if this is because the `liblog_bank.a` doesn't actually contain all the needed symbols, if my includes are bad, or if I did something wrong with the build.

**Comment by jgabaut** [comment]
I did indeed mess up the order of argument in the build.

Was passing `-l:iblog_bank.a` before `-L ./lib`. Closing.

**Comment by khushal-banks** [comment]
> And, you can go ahead and just use `-llog_bank` instead of giving full path.

Correct.

There is also [setup.sh](https://github.com/khushal-banks/log_bank/blob/main/examples/main_example/setup.sh) which does all this automatically for examples.
Then you would need to type `make all` to build both debug and release mode binary for that example. binary will be present in
- bin/Debug/[EXAMPLE name] 
- bin/Release/[EXAMPLE name]
